### PR TITLE
linux ongoing

### PR DESCRIPTION
**Pull request by lytico**
### Description of Change ###

linux ongoing

### Additions made ###
* PageHandler: track api change IPage -> IView
* PageView: refactor MeasureCache - Handling
* GtkPlatformServices: track api changes: remove GetMD5Hash
* ScrollViewHandler: adjust MapOrientation
* EditorHandler: set minimal Width if text is empty
* Controls.Sample.Gtk.csproj: remove reference to Controls.Sample.csproj for the moment (it's not compiling any more, see: #23 )
* adjust gtk-doc urls (new since august 2021: https://developer.gnome.org moved to https://docs.gtk.org)

### CODE REVIEW

**Comment by lytico** [comment]
sorry, forgot to mark as draft

**Comment by redradist** [comment]
@lytico What is the current status of this PR ?

I would like to help, but due to lots of changes, I do not understand where to start ...

**Comment by lytico** [comment]
@redradist try to implement https://github.com/jsuarezruiz/maui-linux/blob/main-linux/src/Core/src/Handlers/TimePicker/TimePickerHandler.Gtk.cs
this handler is currently a stub, so, to get a feeling how handlers work, it should be a good start.
check out branch main-linux: https://github.com/jsuarezruiz/maui-linux/tree/main-linux

to see how could look: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/timepicker

**Comment by lytico** [comment]
closed in favour of https://github.com/jsuarezruiz/maui-linux/pull/24

**Comment by redradist** [comment]
> 
> 
> @redradist try to implement https://github.com/jsuarezruiz/maui-linux/blob/main-linux/src/Core/src/Handlers/TimePicker/TimePickerHandler.Gtk.cs
> this handler is currently a stub, so, to get a feeling how handlers work, it should be a good start.
> check out branch main-linux: https://github.com/jsuarezruiz/maui-linux/tree/main-linux
> 
> to see how could look: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/timepicker

@lytico Thanks I will try !!
Is there anywhere instruction how to install Android workloads to linux ?
I believe it will not work without it, am I right ??

**Comment by redradist** [comment]
@lytico 
Here is what I mean:
```console
  Microsoft.NET.TargetFrameworkInference.targets(93, 5): [NETSDK1013] The TargetFramework value 'net6.0-android' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.
```
But when I try to install `dotnet workload install android`:
```console
Workload installation failed: microsoft.android.sdk.linux::30.0.100-preview.7.110 is not found in NuGet feeds https://api.nuget.org/v3/index.json".
```

And I am stuck ...

**Comment by lytico** [comment]
i'm using Microsoft.Maui.sln, not the Microsoft.Maui-net6.sln. with this, there is no need for .net6-support.

as of android on linux:
i used https://github.com/lytico/xamarin-android-linux to get some sort of android-support on linux, but not the workload.

all of .net6, workloads etc. i wait until the release in november, as there are too much changes at the time, and i've no need for it to develop the maui-gtk-branch at the moment.

**Comment by tracker1** [comment]
Not sure if there's a canonical time picker in Linux/GTK, but, what I believe is the iOS picker looks best for Time... would work well with a mousewheel as well.

For dates, I really like the pattern used in the old MS Ajax Toolkit... where clicking the Month/Year brings you to a month picker, clicking the year, up to a spinner... so spinner for year, month grid for months, and calendar months for picking the date.  With prev/next to the title at each level.

Just my own thoughts on this one.

**Comment by iMonZ** [comment]
> i'm using Microsoft.Maui.sln, not the Microsoft.Maui-net6.sln. with this, there is no need for .net6-support.
> 
> as of android on linux:
> i used https://github.com/lytico/xamarin-android-linux to get some sort of android-support on linux, but not the workload.
> 
> all of .net6, workloads etc. i wait until the release in november, as there are too much changes at the time, and i've no need for it to develop the maui-gtk-branch at the moment.

Hey, dotNet 6 is now in RC
I don’t think that there will be any major changes.
And thanks for your hard work!

**Pull request closed without merging**
