### PR TITLE
gtk ongoing

### PR DESCRIPTION
**Pull request by lytico**
merging main-linux with 

1. a recent maui.main (https://github.com/dotnet/maui/commit/11069875d2b95df9833c6668c3b0cc26f5b18ac7) 
2. plus https://github.com/dotnet/maui/pull/9522

### State

Controls.Samples.Gtk is running

all the rest is WIP

### How to get net6-gtk workload:

clone https://github.com/GtkSharp/GtkSharp branch Develop

```
dotnet tool restore
dotnet cake --BuildTarget=InstallWorkload 
```

Controls.Samples.Gtk screenshot:

grafik

### CODE REVIEW

**Comment by lytico** [comment]
### State

Core is compiling

**Comment by lytico** [comment]
### State

Controls is compiling

**Comment by lytico** [comment]
### State

Controls.Xaml is compiling

**Comment by lytico** [comment]
### State

Controls.Compatibility is compiling

**Comment by lytico** [comment]
### State

Controls.Samples.Gtk is compiling
Controls.Maps is compiling
BlazorWebView is compiling

**Comment by lytico** [comment]
### State

Controls.Samples.Gtk  running

grafik

**Comment by jsuarezruiz** [comment]
> ### State
> Controls.Samples.Gtk running
> 
> grafik

Ready to review/merge?

**Comment by lytico** [comment]
i've little time at the moment ...

**Comment by iMonZ** [comment]
> i've little time at the moment ...

Hey @lytico and @jsuarezruiz and everybody else, thank you so much for your work!
My only question is what is missing before this can be merged?

Thanks

**Comment by knocte** [comment]
> Ready to review/merge?

How can this be tested? If there were clear instructions I'd be down to help :)

**Comment by lytico** [comment]
@knocte check it out, & run src/Controls/samples/Controls.Sample.Gtk

next step would be: try get src/Controls/samples/Controls.Sample to COMPILE
it wouldn't RUN, cause there are missing controls, but it would be helpful to have a compiling Controls.Sample to continue

**Comment by trungnt2910** [comment]
> it wouldn't RUN, cause there are missing controls

I can see that MAUI is a really quicky-evolving platform, so for every version of MAUI added, numerous new controls are added too.

The platform specific portions of controls seem to follow a very specific convention, would a stub generator program (something that guesses the functions needed to be implemented, and then write placeholders that simply `throw NotImplementedException()`) be a useful tool for the porting effort?

**Comment by lytico** [comment]
@trungnt2910 yes, this is the strategy i use.

1) make it COMPILE
the projects compile without errors

2) make it RUN
the project runs without exceptions; this includes "dummy" implementations showing "nothing" but an empty placeholder == stub

3) make it VISIBLE
the controls/views show up something useful, but maybe not all features are implemented

4) make it feature complete
:-) will it ever be?

5) optimize it
sometimes after 3), sometimes after 4). have an implementation that is fast and memory optimized

**Comment by trungnt2910** [comment]
@lytico 

> 1. make it COMPILE
> the projects compile without errors

My point is the rapid evolution of MAUI means that controls and other features are added, making this step harder and harder after rebasing (for example, while some parts of this branch may compile, rebasing it to the `main` branch for .NET 8 might not work, especially after half a year).

Therefore, this project would benefit from a stub generator. The simplest method is to throw a `NotImplementedException` everywhere, but we can customize the stubgen to generate more specific implementations for certain situations in step 2).

I would gladly build and provide an initial implementation of the stubgen for the project if you and other maintainers don't have much time, but I'm asking if using a stub generator is **preferred**, or if you or the other maintainers have **better** solutions for handling missing controls/functions.

**Comment by trungnt2910** [comment]
@YoshiRulz 

> as installing the GTK# workload fails.

Have you tried installing it as root? This workload (and probably official workloads from Microsoft) requires root access to be installed on UNIX-like machines.

> I'm also available to work on Source Generators if that's desired.

What I was talking about are _stub_ generators, those that can semi-automatically insert
```csharp
#if GTK
    throw new NotImplementedException("Code path unimplemented on GTK");
#endif
```
and things like that, and **not** those Roslyn plugins that Microsoft calls "Source Generators".

> Microsoft could easily check for build errors in CI

Yes, they could **easily** check for build errors in the CI (if writing and updating CI scripts for a separate platform is considered _easy_).

But what about _fixing_ the errors? Microsoft doesn't want to spend money on a small market like GTK on Linux, and while waiting for two busy GTK experts to inspect what's wrong Microsoft would rather remove the whole Linux CI.

~~Also if someone really, really needs MAUI on GTK and willing to hire someone I'm happy to take on this issue as a part-time job.~~

**Comment by lytico** [comment]
Controls.Sample is compiling now (but not working)

Ready to review/merge

**Pull request merged**
