### PR TITLE
Gtk.BlazorWebView: Support Blazor Hybrid on Linux / over Gtk 

### PR DESCRIPTION
**Pull request by lytico**
### Description of Change

Implementing 
 Microsoft.AspNetCore.Components.WebView.Gtk.BlazorWebView
 Microsoft.AspNetCore.Components.WebView.Maui.BlazorWebView.Gtk

### Will hopefully fix / implement

https://github.com/dotnet/maui/issues/11738

Fixes #

this is Microsoft.AspNetCore.Components.WebView.Gtk.BlazorWebView in action:

Peek 2023-09-14 03-51

### CODE REVIEW

**Comment by lytico** [comment]
Peek 2023-09-14 03-51

**Comment by jsuarezruiz** [comment]
Nice work here @lytico!, let me know if you need something.

**Comment by charleypeng** [comment]
Nice to see some dev on linux, looking forward

**Comment by charleypeng** [comment]
No good news , the official team said they wont maintain any linux based code

**Comment by charleypeng** [comment]
Microsoft hate linux 👀

**Comment by CommonLoon102** [comment]
> No good news , the official team said they wont maintain any linux based code

How is that news? They have stated this since MAUI has been announced.

**Comment by lytico** [comment]
@CommonLoon102 https://github.com/dotnet/maui/issues/11738#issuecomment-1732013969

**Comment by CommonLoon102** [comment]
> @CommonLoon102 [dotnet#11738 (comment)](https://github.com/dotnet/maui/issues/11738#issuecomment-1732013969)

At least they are consistent with that what they were saying years ago. This reasoning is exactly what I remember from years ago.

**Pull request closed without merging**
