### PR TITLE
[WIP] lytico/gtksharp/init linux DO NOT MERGE

### PR DESCRIPTION
**Pull request by lytico**
DO NOT MERGE!

this PR is here to see what i'm working on 
and to avoid double work of others and me

it will be replaced by a cleaner one later

### CODE REVIEW

**Comment by redjaguar** [comment]
A good list.  Since there are no specific tasks set up yet this has me wondering what I can start working on.

**Comment by lytico** [comment]
@redjaguar it's not ready at all, i've to find out patterns how to implement stuff with minimal effort.
if i got it, i will make a new pull request, with one clean example how to implement a handler.

**Comment by jsuarezruiz** [comment]
@lytico Let me know when you want a review or feedback.

**Comment by lytico** [comment]
this is the Core part of the changes, ready to review:
https://github.com/jsuarezruiz/maui-linux/pull/5

**Pull request closed without merging**
