### PR TITLE
Upgrade to Maui Version 8.0.3 & net8.0

### PR DESCRIPTION
**Pull request by lytico**
### Description of Change

Based on Version 8.0.3 https://github.com/dotnet/maui/releases/tag/8.0.3
merge branch https://github.com/dotnet/maui/commit/0d64894f82723172992a17bc3d1764e5af0e53d6

how to get it compile:

you have to install workload android, otherwise build fails with rider!

checkout https://github.com/lytico/GtkSharp/tree/lytico/net8

```

sudo -s
dotnet workload install android
git clone https://github.com/lytico/GtkSharp.git -b lytico/net8
cd GtkSharp
dotnet tools restore
dotnet cake --BuildTarget=UninstallWorkload 
dotnet cake --BuildTarget=InstallWorkload 
cd ..
rm -R GtkSharp
```

grafik

### CODE REVIEW

**Comment by lytico** [comment]
@jsuarezruiz please a short statement to future of maui-linux
i understand that there are no resources to merge into maui https://github.com/dotnet/maui as of
https://github.com/dotnet/maui/issues/11738#issuecomment-1732013969
but is there a future of this fork?

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz please a short statement to future of maui-linux i understand that there are no resources to merge into maui https://github.com/dotnet/maui as of [dotnet#11738 (comment)](https://github.com/dotnet/maui/issues/11738#issuecomment-1732013969) but is there a future of this fork?

I'm on vacation right now but I'll talk about it with the MAUI team soon when I get back. At the community level I am open to proposals or ideas.

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz please a short statement to future of maui-linux i understand that there are no resources to merge into maui https://github.com/dotnet/maui as of [dotnet#11738 (comment)](https://github.com/dotnet/maui/issues/11738#issuecomment-1732013969) but is there a future of this fork?

David Ortinau and other PMs should decide what to do. In the past when working in Xamarin.Forms GTK was merged into the Xamarin.Forms repo but once the entire implementation was completed.

**Comment by hansmbakker** [comment]
> In the past when working in Xamarin.Forms GTK was merged into the Xamarin.Forms repo but once the entire implementation was completed

@jsuarezruiz this sentence seems to be cut off - could you please check if this was what you meant to write?

**Comment by lytico** [comment]
it means that:
there has to be a complete implementation of Maui.Gtk before it could be merged into the main branch.
this was the way how it was done with the Xamarin.Forms - Gtk-Implementation

**Comment by hansmbakker** [comment]
Ah, I understand it now, thanks

**Comment by malix0** [comment]
@lytico I remember you posted a link with the status of components, but I'm not sure was related to MAUI Linux or Gtk

**Comment by lytico** [comment]
status is something like this: https://github.com/lytico/maui/blob/lytico/merge/main231023/Status.md

**Comment by jsuarezruiz** [comment]
> it means that: there has to be a complete implementation of Maui.Gtk before it could be merged into the main branch. this was the way in the past how it was done with the Xamarin.Forms - Gtk-Implementation

Exactly that, thanks @lytico for the answer.

**Comment by hifron** [comment]
Ask MS if you could merge this into Maui, but problem is legal because WinForms on other platforms than Windows requires special care or maybe permission. But if you could make deal with MS and you agree to support Maui under Linux for the long term and maybe community would agree for some special care to handle bugs, Microsoft Legal Review Process maybe could approve this(maybe from beginning requiring Windows license or other licensing) but probably would this go further if success.. But this repository is now violating something but problem is that that are simply more problems and no money only otherwise...

There are other possibilities to make Desktop Linux Apps, and if MS has problems with Maui(or even WinForms) under Linux, it is for some purpose...

**Comment by lytico** [comment]
closing because outdated

a new PR will be prepared based on 

https://github.com/lytico/maui/tree/lytico/gtk-ongoing

**Comment by DamianSuess** [comment]
@lytico looking forward to your PR. Just took a look at what you have going on, holy geez amazing!!
Really hope the MAUI team accepts your upcoming PR into the mainstream. 2 years back, we had to pivot to a different Linux UI-supporting solution due to it not being carried forward from Xamarin.Forms. Can't wait 🙏

**Comment by lytico** [comment]
the pr is here: https://github.com/jsuarezruiz/maui-linux/pull/66

**Comment by DamianSuess** [comment]
Just made my day! Have a great weekend

**Comment by lytico** [comment]
> @DamianSuess  Really hope the MAUI team accepts your upcoming PR into the mainstream. 

they won't. it's to much work to get a nearby production version.

i estimate around 600 - 800 hours to finalize it.

the  whole layout process is a mess - starting with Layout-View and others.

there is a lot of mini mini, but time consuming stuff to do.

alone the BorderView - although it's a minimal implementation - took me 20 hours.

**Comment by malix0** [comment]
It's a shame, I see lot of people, shure also me, that are following Linux related MAUI issues. As you said 800 hours are too much for a single developer, but if the work can be splitted between more people, it maybe can be achieved. But I think that this is difficult to manage, cause there are a lot of things that need to be studied. MAUI architecture, GTK, WebView and related things. Then a coordination is needed. But if someone else is interested I'm here to learn and help.

**Pull request closed without merging**
